import { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Classic Oversized Blazer",
    price: 149.0,
    originalPrice: 199.0,
    image: "https://picsum.photos/seed/blazer/400/500",
    category: "Outerwear",
    description:
      "A relaxed oversized blazer that works for both casual and formal occasions. A wardrobe essential.",
    rating: 4.5,
    reviewCount: 128,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Beige"],
  },
  {
    id: "2",
    name: "Soft Cashmere Knit Sweater",
    price: 98.0,
    image: "https://picsum.photos/seed/cashmere/400/500",
    category: "Tops",
    description: "A soft cashmere blend knit sweater. Warm yet lightweight for everyday comfort.",
    rating: 4.8,
    reviewCount: 256,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Ivory", "Gray", "Pink"],
  },
  {
    id: "3",
    name: "Wide Fit Cotton Pants",
    price: 68.0,
    image: "https://picsum.photos/seed/widepants/400/500",
    category: "Bottoms",
    description:
      "Wide-leg cotton pants with a relaxed silhouette. Perfect for comfortable daily outfits.",
    rating: 4.3,
    reviewCount: 89,
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black", "Khaki"],
  },
  {
    id: "4",
    name: "Linen Blend Shirt Dress",
    price: 128.0,
    originalPrice: 158.0,
    image: "https://picsum.photos/seed/shirtdress/400/500",
    category: "Dresses",
    description:
      "A breezy linen blend shirt dress. Features an adjustable waist belt for a custom fit.",
    rating: 4.6,
    reviewCount: 167,
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Light Blue"],
  },
  {
    id: "5",
    name: "Minimal Leather Tote Bag",
    price: 189.0,
    image: "https://picsum.photos/seed/totebag/400/500",
    category: "Accessories",
    description: "A clean-lined soft leather tote bag with generous storage space.",
    rating: 4.7,
    reviewCount: 203,
    colors: ["Black", "Brown", "Tan"],
  },
  {
    id: "6",
    name: "Classic Chelsea Boots",
    price: 158.0,
    originalPrice: 198.0,
    image: "https://picsum.photos/seed/chelseaboot/400/500",
    category: "Shoes",
    description:
      "Classic Chelsea boots that pair effortlessly with any outfit. A timeless staple.",
    rating: 4.4,
    reviewCount: 145,
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Black", "Brown"],
  },
  {
    id: "7",
    name: "Wool Blend Scarf",
    price: 52.0,
    image: "https://picsum.photos/seed/woolscarf/400/500",
    category: "Accessories",
    description: "A soft wool blend scarf. Warm and stylish with a refined design.",
    rating: 4.9,
    reviewCount: 312,
    colors: ["Charcoal", "Camel", "Burgundy"],
  },
  {
    id: "8",
    name: "Straight Fit Denim Jeans",
    price: 89.0,
    image: "https://picsum.photos/seed/straightjeans/400/500",
    category: "Bottoms",
    description:
      "Classic straight-fit denim jeans that go with everything. A true everyday essential.",
    rating: 4.5,
    reviewCount: 198,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Indigo", "Black", "Light Wash"],
  },
  {
    id: "9",
    name: "Oversized Zip-Up Hoodie",
    price: 85.0,
    image: "https://picsum.photos/seed/hoodie/400/500",
    category: "Outerwear",
    description:
      "A cozy oversized zip-up hoodie. A must-have for relaxed casual looks.",
    rating: 4.2,
    reviewCount: 176,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gray", "Black", "Navy"],
  },
  {
    id: "10",
    name: "Silk Blouse",
    price: 139.0,
    originalPrice: 179.0,
    image: "https://picsum.photos/seed/silkblouse/400/500",
    category: "Tops",
    description:
      "A luxurious silk blouse. Versatile enough for the office or a night out.",
    rating: 4.7,
    reviewCount: 221,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Ivory", "Blush", "Black"],
  },
];

export function getProduct(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}
